### PR TITLE
Fix #381: Coverity: Unlogged security exception

### LINKED ISSUE #381: Coverity: Unlogged security exception
### Task specification

_No response_

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: rest-client-base/src/main/java/com/wultra/core/rest/client/base/util/SslUtils.java [hunk 1]
```diff
@@ -145,27 +145,30 @@ public static SslContext prepareSslContext(RestClientConfiguration config) throw
                                     return trustStore.isCertificateEntry(t);
                                 } catch (KeyStoreException ex) {
                                     keyStoreExceptions.add(ex);
+                                    logger.error("Failed to check if certificate is in truststore: {}", t, ex);
```
Comment (banterCZ) [inline rest-client-base/src/main/java/com/wultra/core/rest/client/base/util/SslUtils.java:148]: I still do not like that `filter` has a side-effect as modifying the collection, but let's do as a small fix as possible.

**Review by romanstrobl — APPROVED** [review]
Looks OK.
